name: firestore_mock
description: Google Cloud Firestore Test Helpers
version: 0.0.2
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>
homepage: https://github.com/jarekb123/firestore_mock

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.6
  cloud_firestore: ^0.9.13+1
  kt_dart: ^0.6.1
  mockito: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.3